### ISSUE TITLE
can you tune the player to 432hz

### ISSUE THREAD

**Issue by skypce** [pmarks-net/chromadoze#15]
432hz is the frecuency of universe. All music is tuned to 440 hz by default.
https://ask.audio/articles/5-reasons-to-consider-tuning-to-432hz-for-meditation-music

Thank you Guys.

**Comment by pmarks-net** [comment]
[wat](https://www.urbandictionary.com/define.php?term=wat)

**Comment by cosmopol** [comment]
The sound frequency of 440 Hertz equates to the pitch 'A' on every musical instrument. 432 Hertz as universal sound frequency sounds very esoteric to me... Sorry, this is not a philosophy forum...
