### ISSUE TITLE
Sponsorship?

### ISSUE THREAD

**Issue by kousu** [pmarks-net/chromadoze#23]
I've probably spent more time in this app than most of others I have on my phone. It's really helped my life out over the last 6 years. I would love to be able to chip in either on Github Sponsors of Liberapay or Flattr or something.

**Comment by pmarks-net** [comment]
I don't really need money for this; it's been "basically done" for years, aside from some occasional turmoil in the Android APIs.  The nice thing about local software is that your electricity covers the operational costs.

**Comment by kousu** [comment]
Well then please have my deep thanks.

It's improved my sleep ever since I found it in F-Droid. If I've stayed up too late working I know that ChromaDoze is there to help settle me down. I think it's even made me dream better. And I love that I can leave it on all night even unplugged and not worry about draining my battery. Thank you!

**Comment by kenwud** [comment]
I would like to second kousu's thanks. what a neat interesting app. thank you for one making it, and two allowing it to be open source.
