### ISSUE TITLE
Feature request: sleep timer / auto shut-off

### ISSUE THREAD

**Issue by GoogleCodeExporter** [pmarks-net/chromadoze#3]
```
What steps will reproduce the problem?
1. NA

What is the expected output? What do you see instead?

May you please implement a sleep timer or auto-off feature please?

Many thanks,

JA.
```

Original issue reported on code.google.com by `jolyon.a...@gmail.com` on 8 Mar 2013 at 7:44

**Comment by snan** [comment]
The truth is that those third party apps aren't in F-droid.
Lots of Android phones (or Android forks) aren't using Google Play.
I've used noise sources that mildly fade out after a while. (Like something quickly whipped up with ladspa and audacity or ams.) Love them, but prefer how Chroma Doze sounds.
Anyone figure out a solution to this? Every time you update Chroma Doze, I have my fingers tightly crossed.

**Comment by snan** [comment]
To clarify, me stressing out over the phone using up its battery all night is part of it.
The other part is I want to use asynchronous wave forms (such as noise) sparingly. They really calm me down, but can harm hearing long term.
